;NAME:: LUNGADE KIRAN SANJAY
;ROLL NO.:: 39
;BATCH:: S2
;PROGRAM TO REVERSE THE STRING AND CONVERT UPPER CASE LETTER TO LOWER CASE LETTER


	EXTRN LOWER_UPPER:FAR
	PUBLIC P5,STR1BUFF,STR1,STR3

INCLUDE MACRO.ASM

DATASEG1 SEGMENT
	STR1BUFF DB 20,0
	STR1 DB 20 DUP(0),'$'
	STR2 DB 20 DUP(0),'$'
	STR3 DB 20 DUP(0),'$'

	P1 DB 10,13,'ENTER THE STRING : $'
 	P2 DB 10,13,'REVERSE OF THE STRING IS : $'
	P3 DB 10,13,'STRING CONVERTED IS : $'
	P4 DB 10,13,'REVERSING THE STRING : $'
	P5 DB 10,13,'CONVERTED STRING FROM LOWER TO UPPER IS : $'

DATASEG1 ENDS

STACKSEG1 SEGMENT STACK
	DW 100 DUP(0)
	ST_PTR DW 0

STACKSEG1 ENDS

CODESEG1 SEGMENT

	ASSUME DS:DATASEG1,CS:CODESEG1,SS:STACKSEG1

BEGIN: MOV AX,DATASEG1
	MOV DS,AX
	MOV AX,STACKSEG1
	MOV SS,AX
	MOV SP,OFFSET ST_PTR
	
	DISPSTR P1
	INPUTSTR STR1BUFF

	;MANIPULATE STRINGS
	CALL REVERSE_STR

	DISPSTR P2
	DISPSTR STR2

	;CALL SECOND PROCEDURE
	CALL LOWER_UPPER
	DISPSTR P3
	DISPSTR STR3
	MOV AX,4C00H
	INT 21H ;END OF MAIN PROGRAM

REVERSE_STR PROC NEAR
	DISPSTR P4
	MOV SI,OFFSET STR1
	MOV DI,OFFSET STR2
	MOV CX,0000H
	MOV CL,STR1BUFF+1
	ADD SI,CX

BACK: DEC SI
	MOV AL,[SI]
	MOV [DI],AL
	INC DI
	LOOP BACK
	RET

REVERSE_STR ENDP

CODESEG1 ENDS
	END BEGIN



;UPPER TO LOWER CASE FILE
	INCLUDE MACRO.ASM
	PUBLIC LOWER_UPPER
	EXTRN P5:BYTE,STR1BUFF:BYTE,STR1:BYTE,STR3:BYTE

DATASEG1 SEGMENT
	DB 10 DUP(0)
DATASEG1 ENDS
	
CODESEG2 SEGMENT
	ASSUME CS:CODESEG2,DS:DATASEG1
 
LOWER_UPPER PROC FAR
	DISPSTR P5
	MOV SI,OFFSET STR1
	MOV DI,OFFSET STR3
	MOV CX,0000H
	MOV CL,STR1BUFF+1

BACK: MOV AL,[SI]
	CMP AL,'a'
	JB SKIP
	CMP AL,'z'
	JA SKIP
	SUB AL,20H

SKIP: MOV [DI],AL
	INC SI
	INC DI
	LOOP BACK
	RET
 LOWER_UPPER ENDP
CODESEG2 ENDS
	END


;MACRO FILE
INPUTSTR MACRO BUFFADDR
	MOV AH,0AH
	MOV DX,OFFSET BUFFADDR
	INT 21H
	ENDM

DISPSTR MACRO STRADDR
	MOV AH,09H
	MOV DX,OFFSET STRADDR
	INT 21H
	ENDM