;NAME:: LUNGADE KIRAN SANJAY
;BATCH:: S2
;ROLL NO.:: 39
;PROGRAM FOR ADDITION OF 8 DIGIT NUMBERS


INPUTSTR MACRO BUFFADDR
	MOV AH,0AH
	MOV DX,OFFSET BUFFADDR
	INT 21H
	ENDM

DISPSTR MACRO STRADDR
	MOV AH,09H
	MOV DX,OFFSET STRADDR
	INT 21H
	ENDM

DATASEG1 SEGMENT
	N1BUFF DB 9,0
	N1 DB 31H,32H,33H,34H,35H,36H,37H,38H,'$'
	N2BUFF DB 9,0
	N2 DB 31H,31H,31H,31H,31H,37H,37H,39H,'$'
	SUM DB 9 DUP('0'),'$'
	CARRY DB 0, '$'
	STR1 DB 10,13,'First 8-digit number : $'
	STR2 DB 10,13,'Second 8-digit number : $'
	STR3 DB 10,13,'Addition of numbers is: $'

DATASEG1 ENDS

CODESEG1 	SEGMENT
		ASSUME DS:DATASEG1,CS:CODESEG1
BEGIN: MOV AX,DATASEG1
	MOV DS,AX

	DISPSTR STR1
	INPUTSTR N1BUFF

	DISPSTR STR2
	INPUTSTR N2BUFF

	;convert ASCII to BCD
	MOV SI,OFFSET N1
	MOV DI,OFFSET N2
	MOV CX,0008H

BACK: AND BYTE PTR[SI],0FH
	AND BYTE PTR[DI],0FH
	INC SI
	INC DI
	LOOP BACK
	
	;ADD NUMBERS
	DEC SI
	DEC DI
	MOV BX,OFFSET SUM+8
	MOV CX,0008

BACK1: MOV AL,[SI]
	ADD AL,[DI]
	ADD AL,CARRY
	DAA
	MOV CARRY,0
	CMP AL,09
	JBE SKIP
	MOV CARRY,1
	AND AL,0FH

SKIP:
	ADD AL,30H
	MOV[BX], AL
	DEC SI
	DEC DI 
	DEC BX 
	LOOP BACK1 
	DISPSTR STR3
	DISPSTR SUM

	MOV AX,4C00H
	INT 21H

CODESEG1 	ENDS
		END BEGIN