;NAME:: LUNGADE KIRAN SANJAY
;ROLL NO.:: 39
;BATCH:: S2
;TITLE:: CONVERTING BINARY NUMBER TO HEXADECIMAL NUMBER


INPUTSTR	MACRO BUFFADDR
		MOV AH,0AH
	MOV DX,OFFSET BUFFADDR
	INT 21H
	ENDM

DISPSTR 	MACRO STRADDR
		MOV AH,09H
		MOV DX,OFFSET STRADDR
		INT 21H
		ENDM

DATASEG1 SEGMENT
	BINBUFF DB 9,0
	BINARY DB 9 DUP(0),'$'
	HEX DB '00H','$'
	
	STR1 DB 10,13,'First 8-digit binary number : $'
 	STR2 DB 10,13,'Equivalent hexadecimal number is: $'

DATASEG1 ENDS

CODESEG1 SEGMENT
	
	ASSUME DS:DATASEG1,CS:CODESEG1

BEGIN: MOV AX,DATASEG1
	MOV DS,AX

	DISPSTR STR1
	INPUTSTR BINBUFF

	;CONVERT BINARY TO HEXADECIMAL
	MOV SI,OFFSET BINARY
	MOV CX,04
	MOV DL,00H

BACK: MOV AL,[SI]
	AND AL,01H
	ROL DL,1
	OR DL,AL
	INC SI
	LOOP BACK
	ADD DL,30H
	MOV HEX,DL
	MOV CX,04
	MOV DL,00H

BACK1: MOV AL,[SI]
	AND AL,01H
	ROL DL,1
	OR DL,AL
	INC SI
	LOOP BACK1
	ADD DL,30H
	MOV HEX+1,DL

	DISPSTR STR2
	DISPSTR HEX
	
	INT 21H

CODESEG1 ENDS
	END BEGIN