; NAME: LUNGADE KIRAN SANJAY
; ROLL NO :39
; BATCH: S2
; TITLE :8051 MICROCONTROLLER INTERFACING WITH LCD 

;******************PROGRAM***************** 

	RS EQU P3.2 
	EN EQU P3.3 
	LCD EQU P0 
	ORG 00H 
	SJMP MAIN 
	ORG 40H 

	MAIN: MOV A, #38H 			; INTI LCD 2 LINES 5X7 MATRIXS 
		ACALL COMMAND 			; CALL CIMMAND SUBROUTINE 
		MOV A, #0EH 			; DISPLAY ON CURSOR ON 
		ACALL COMMAND MOV A, #01H	; CLEAR LCD ACALL COMMAND 
		MOV A, #06H 			; SHIFT CURSOR RIGHT 
		ACALL COMMAND MOV A, #80H	; FORCE CURSOR TO BEGING TO 1ST LINE 
		ACALL COMMAND 
		MOV A, #'S' 
		ACALL DATAWR 
		MOV A, #'R' 
		ACALL DATAWR 
		MOV A, #'E' 
		ACALL DATAWR 
		MOV A, #'S' 
		ACALL DATAWR 

	HERE:
		SJMP HERE ; STAY HERE 

	COMMAND:
		CLR RS 				; RS=0 TO SELECT COMMAND REGISTER 
		SETB EN 				; EN=1 HIGH TO LOW PULSE 
							; INTERNAL LATCH OF LCD 
		MOV LCD, A
		CLR EN 
		ACALL DELAY 
		RET 
	
	DELAY:
		MOV R2, #50 

	ABC:
		MOV R3, #255 

	XYZ:
		DJNZ R2, ABC
		RET 

	DATAWR:
		SETB RSSETB EN 
		MOV LCD, A
		CLR EN 
		ACALL DELAY 
		RET 
		END